language: python

python:
  - "3.7.3"

services:
  - postgresql 

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -U postgres travis_ci_test
  - \d
  - create table usuarios (ID_Usu serial primary key not null, name text, pw text, progres text, marca text, tipo text, cigar integer);
  - \d
  - insert into usuarios (name,pw,progres,marca,tipo,cigar) VALUES('Usuario 1','123','23','MarcaA','Industrial',22);
  - select * from usuarios
  - \q
  - exit
# command to install dependencies
install:
  - pip3 install -r requirements.txt
script: pytest -v test.py
