language: python

python:
  - "3.7"

# command to install dependencies
install:
  #- pip3 install -r requirements.txt
  - make dependences
services:
  - postgresql
    
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  
 
# command to run tests
script: 
  - make ini_ap
  - make status
  - make -B test

after_success:
  - make stop_app
  - make delete_app
  
  - cd ./test  
  - bash <(curl -s https://codecov.io/bash) -t CODECOV_TOKEN -f coverage.xml

  - coveralls
