language: python

python:
  - "3.7.3"

services:
  - postgresql 

before_intall:
  - sed -e 's/^port.*/port = 5433/' /etc/postgresql/9*/main/postgresql.conf > postgresql.conf 
  - sudo chown postgres postgresql.conf
  - sudo mv postgresql.conf /etc/postgresql/9*/main
  - sudo service postgresql start 9*
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - psql -d travis_ci_test -c 'create table usuarios (ID_Usu serial primary key not null, name text,pw text, progres text, marca text, tipo text, cigar integer);' -U postgres

  - psql -d 'travis_ci_test' -c "INSERT INTO usuarios(name, pw, progres, marca, tipo, cigar) VALUES ('Usuario 1',md5('abc123'),'1995-11-06T23:20:50', 'MarcaA', 'Industrial', 22);" -b -U postgres
  - psql -d 'travis_ci_test' -c "select * from usuarios;" -U postgres

  
# command to install dependencies

install:
  - pip3 install -r requirements.txt
script: cd ./test && pytest -v test.py 
