language: python

python:
  - "3.7.3"

node_js:
  - node

install:
  - npm ci 
services:
  - postgresql 

before_intall:
  - sed -e 's/^port.*/port = 5433/' /etc/postgresql/9*/main/postgresql.conf > postgresql.conf 
  - sudo chown postgres postgresql.conf
  - sudo mv postgresql.conf /etc/postgresql/9*/main
  - sudo service postgresql start 9*
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -d travis_ci_test -c 'create table usuarios (ID_Usu serial primary key not null, name text,pw text, progres text, marca text, tipo text, cigar integer);' -U postgres

  - psql -d 'travis_ci_test' -c "INSERT INTO usuarios(name, pw, progres, marca, tipo, cigar) VALUES ('Usuario 1',md5('abc123'),'1995-11-06T23:20:50', 'MarcaA', 'Industrial', 22);" -b -U postgres
  - psql -d 'travis_ci_test' -c "select * from usuarios;" -U postgres

  
# command to install dependencies

install:
  - pip3 install -r requirements.txt
  - pip3 install codecov
  - pip3 install pytest-cov
  - pip3 install python-coveralls
script: 
  - cd ./test && pytest -s -v test.py 
  - coverage run test.py
  - coverage report -m
  - coverage html
  - py.test coveralls/tests.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing
  
after_success:
  - codecov -F unittests -t d083f686-8673-49f1-8b91-24afe8872f17
  - coveralls
  #- coverage run test.py
  #- coverage report -m test.py 
  #- coverage run -m unittest discover
  #- bash <(curl -s https://codecov.io/bash)
  #- bash <(curl -s https://codecov.io/bash) -c -F integration

