language: python

python:
  - "3.5"

virtualenv:
  system_site_packages: true 
node_js:
  - node

install:
  - npm ci 
services:
  - postgresql 

before_intall:
  - sed -e 's/^port.*/port = 5433/' /etc/postgresql/9*/main/postgresql.conf > postgresql.conf 
  - sudo chown postgres postgresql.conf
  - sudo mv postgresql.conf /etc/postgresql/9*/main
  - sudo service postgresql start 9*
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -d travis_ci_test -c 'create table usuarios (ID_Usu serial primary key not null, name text,pw text, progres text, marca text, tipo text, cigar integer);' -U postgres

  - psql -d 'travis_ci_test' -c "INSERT INTO usuarios(name, pw, progres, marca, tipo, cigar) VALUES ('Usuario 1',md5('abc123'),'1995-11-06T23:20:50', 'MarcaA', 'Industrial', 22);" -b -U postgres
  - psql -d 'travis_ci_test' -c "select * from usuarios;" -U postgres

  
# command to install dependencies

install:
  - pip3 install -r requirements.txt
  - pip3 install codecov
  - pip3 install pytest-cov
  - pip3 install python-coveralls
  - pip3 install coveralls
script: 
  - cd ./test && pytest -s -v test.py 
  - coverage run test.py
  - coverage report -m
  - coverage xml
  #- py.test coveralls/tests.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing
  
  

  
after_success:
  - bash <(curl -s https://codecov.io/bash) -t d083f686-8673-49f1-8b91-24afe8872f17 -f coverage.xml
  - coveralls
  