language: python

python:
  - "3.7"

# command to install dependencies
install:
  - pip3 install -r requirements.txt
services:
  - postgresql
    
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  
 
# command to run tests
script: 
  - make test
  - make coverage
  - make ini_ap
  - make status
  - make stop_app
  - make delete_app

after_success:
  - make codecov
  
