language: python

python:
  - "3.7"

# command to install dependencies
install:
  #- pip3 install -r requirements.txt
  - make dependences
services:
  - postgresql
    
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  
 
# command to run tests
script: 
  - make ini_ap
  - make status
  - make -B test
  - make -B test_app
  

after_success:
  - make stop_app
  - make delete_app
  - make codecov
