{
    "codecov": {
        "require_ci_to_pass": true
        
        
    }, 
    "comment": {
        "behavior": "default", 
        "layout": "reach,diff,flags,tree", 
        "require_changes": false
    }, 
    "coverage": {
        "precision": 2, 
        "range": [
            70.0, 
            100.0
        ], 
        "round": "down", 
        "status": {
            "changes": false, 
            "patch": true, 
            "project": true
        }
    }, 
    "parsers": {
        "gcov": {
            "branch_detection": {
                "conditional": true, 
                "loop": true, 
                "macro": false, 
                "method": false
            }
        }
    }
    
    
}
