#	#
# Check https://circleci.com/docs/2.0/language-python/ 
#	#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
    working_directory: ~/prueba_travis
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            
            make dependences
            
      - run:
          name: install npm
          command: npm install npm@latest -g

      - run:
          name: isntall pm2
          command: npm install pm2 -g
            # sudo pip3 install pipenv
            # sudo pipenv install
            # sudo pip3 install -U pytest
            # sudo pip3 install -r requirements.txt
            # sudo pip install -r requirements.txt
            # sudo pip3 install codecov
            # sudo pip3 install pytest-cov
            # sudo pip3 install pytest-circleci
            # sudo pip3 install python-coveralls
            # sudo pip3 install coveralls
        
      - run:
          name: init app
          command: make ini_ap
      
      - run:
          name: status app
          command: make status
      
      - run:
          name: tests
          command: make -B test     
      
      - run:
          name: stop app
          command: make stop_app

      - run:
          name: delete app
          command: make delete_app
  
      - save_cache: # cache Python dependencies using checksum of Pipfile as the cache-key
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      
      
      
   
      - store_artifacts:
          path: test-reports
          destination: test-reports
