# This code is licensed from CircleCI to the user under the MIT license. See
# https://circleci.com/orbs/registry/licensing for details.
commands:
  install-deps:
    description: Install packages from requirements.txt via Pip.
    parameters:
      local:
        default: true
        description: Install packages for local user, not globally. Defaults to true.
        type: boolean
    steps:
    - run:
        command: |
          if << parameters.local >>; then
            pip install --user -r requirements.txt
          else
            pip install -r requirements.txt
          fi
        name: Install Dependencies
  load-cache:
    description: Load cached Pip packages.
    parameters:
      key:
        default: pip
        description: The cache key to use. The key is immutable.
        type: string
    steps:
    - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
  save-cache:
    description: Save Pip packages to cache.
    parameters:
      key:
        default: pip
        description: The cache key to use. The key is immutable.
        type: string
    steps:
    - save_cache:
        - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
        paths:
        - /home/circleci/.local/lib/
description: Common CircleCI tasks for the Python programming language.
examples:
  working_directory: ~/prueba_travis
    description: |
     working with the Pip cache on CircleCI to speed up builds.
      
    usage:
      jobs:
        build:
          executor: python/default
          steps:
          - checkout
          - python/load-cache
          - python/install-deps
          - python/save-cache
          - run:
              command: |
                # pytest would be a dep in requirements.txt
                cd ./test && pytest -s -v test.py 
              name: Test
      orbs:
        python: circleci/python@0.1
      version: 2.1
      workflows:
        main:
          jobs:
          - build
executors:
  default:
    description: The official CircleCI Python Docker image.
    docker:
    - image: circleci/python:3.6.1
    parameters:
      tag:
        default: latest
        description: The `circleci/python` Docker image version tag.
        type: string
version: 2.1
